esphome:
  name: meshtastic1
  friendly_name: meshtastic1

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source: github://Andrik45719/esphome-meshtastic@main
    components: [meshtastic]
    refresh: 24h

logger:

api:
  encryption:
    key: "your_api_key_if_needed"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  output_power: 9dB
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: meshtastic
    password: !secret wifi_password

captive_portal:

web_server:

# Configure SPI for LoRa radio
spi:
  clk_pin: GPIO4
  mosi_pin: GPIO6
  miso_pin: GPIO5

# Configure LoRa radio (SX1276 example for Ekaterinburg location)
sx127x:
  id: lora_radio
  cs_pin: GPIO7
  rst_pin: GPIO3
  dio0_pin: GPIO10
  #dio1_pin: GPIO0
  frequency: 868.825MHz
  spreading_factor: 9
  bandwidth: 250_0kHz
  coding_rate: CR_4_5
  modulation: LORA
  preamble_size: 16
  sync_value: 0x2b
  rx_start: true
  crc_enable: true
  pa_power: 17
  pa_pin: BOOST

# Configure Meshtastic component
meshtastic:
  - id: mesh_node
    lora: lora_radio
    hw_model: 39  # DIY_V1
    hop_limit: 7
    ok_to_mqtt: true
    # Configure channels
    channels:
      - name: MediumFast
        psk: "AQ=="
      - name: XXXX #name of yours private channel
        psk: !secret priv_channel_public_key

    # Configure this node
    nodes:
      - node_number: 00000000 #change to autogenerated at first boot
        name: "Node name"
        short_name: "Node short name"
        private_key: !secret node_private_key
        public_key: !secret node_public_key
    position:
      latitude:  AA.BBBB
      longitude: CC.DDDD
      altitude: EEEE
      broadcast_interval: 3h
    on_packet:
      then:
        - lambda: |-
            ESP_LOGD("id_mesh", "Packet from %08X to %08X port %d %s", from, to, portnum, format_hex(data).c_str());
            if (portnum == meshtastic_PortNum_TEXT_MESSAGE_APP) {
            }

# Send text messages via button press
button:
  - platform: template
    id: door
    name: "Door open"
    on_press:
      then:
        - meshtastic.send_text_message:
            id: mesh_node
            channel: #name of yours private channel
            text: "Door open"
  - platform: template
    id: waterleak
    name: "Water leak on kitchen"
    on_press:
      then:
        - meshtastic.send_text_message:
            id: mesh_node
            channel: #name of yours private channel
            text: "Water leak on kitchen"

  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "RSSI level"
    update_interval: 180s

time:
  - platform: homeassistant
